### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Yonee3** [MHProDev/MHDDoS#109]
proxies error

**Comment by bntr00t** [comment]
More info? Screenshot?

**Comment by Yonee3** [comment]
![image](https://user-images.githubusercontent.com/96109135/153694808-37d806ad-eb90-4b31-916a-e0b527e226f3.png)
this is the error how to fix it?

**Comment by Yonee3** [comment]
why is there no proxy when I attack?

**Comment by ninjutsudev** [comment]
> why is there no proxy when I attack?

Lack of proxies I doubt it, it always finds lists with an average of 3000 to 7000 proxies and of them the fastest ones are usually an average of 30-70.

**Comment by MHProDev** [comment]
#111
