### ISSUE TITLE
Issues with checker

### ISSUE THREAD

**Issue by SlimJUC** [MHProDev/MHDDoS#111]
the checker always has issues

if you can make option to skip the proxy check. and go straight to using proxy in file specified

errors:

```
# python3 start.py CFB https://exitus.me 5 500 a.txt 60 900
{'type': 5, 'url': 'https://api.proxyscrape.com/?request=displayproxies&proxytype=socks5', 'timeout': 5}
{'type': 5, 'url': 'https://www.proxy-list.download/api/v1/get?type=socks5', 'timeout': 5}
{'type': 5, 'url': 'https://gist.githubusercontent.com/Azuures/1e0cb7a1097c720b4ed2aa63acd82179/raw/97d2d6a11873ffa8ca763763f7a5dd4035bcf95f/fwefnwex', 'timeout': 5}
{'type': 5, 'url': 'https://www.proxyscan.io/download?type=socks5', 'timeout': 5}
{'type': 5, 'url': 'https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/socks5.txt', 'timeout': 5}
2,941 Proxies are getting checked, this may take awhile !
Proxy Check failed, Your network may be the problem | The target may not be available. 
```

**and**

```
# python3 start.py CFB https://exitus.me 5 972 1.txt 1000 1000
WARNING! RPC (Request Pre Connection) is higher than 100
WARNING! The file doesn't exist, creating files and downloading proxies.
{'type': 5, 'url': 'https://api.proxyscrape.com/?request=displayproxies&proxytype=socks5', 'timeout': 5}
{'type': 5, 'url': 'https://www.proxy-list.download/api/v1/get?type=socks5', 'timeout': 5}
{'type': 5, 'url': 'https://gist.githubusercontent.com/Azuures/1e0cb7a1097c720b4ed2aa63acd82179/raw/97d2d6a11873ffa8ca763763f7a5dd4035bcf95f/fwefnwex', 'timeout': 5}
{'type': 5, 'url': 'https://www.proxyscan.io/download?type=socks5', 'timeout': 5}
{'type': 5, 'url': 'https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/socks5.txt', 'timeout': 5}
2,934 Proxies are getting checked, this may take awhile !
Traceback (most recent call last):
  File "start.py", line 849, in <module>
    Proxies = ProxyManager.checkAll(Proxies, url.human_repr(), 1, threads)
  File "start.py", line 577, in checkAll
    with ProxyManager.poolcontext(min(len(proxie), threads)) as pool:
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "start.py", line 564, in poolcontext
    pool = Pool(*args, **kwargs)
  File "/usr/lib/python3.8/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 212, in __init__
    self._repopulate_pool()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.8/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 69, in _launch
    child_r, parent_w = os.pipe()
OSError: [Errno 24] Too many open files
```
I will try fix this temporarily and issue a pull request

**Comment by ninjutsudev** [comment]
> the checker always has issues
> 
> if you can make option to skip the proxy check. and go straight to using proxy in file specified
> 
> errors:
> 
> ```
> # python3 start.py CFB https://exitus.me 5 500 a.txt 60 900
> {'type': 5, 'url': 'https://api.proxyscrape.com/?request=displayproxies&proxytype=socks5', 'timeout': 5}
> {'type': 5, 'url': 'https://www.proxy-list.download/api/v1/get?type=socks5', 'timeout': 5}
> {'type': 5, 'url': 'https://gist.githubusercontent.com/Azuures/1e0cb7a1097c720b4ed2aa63acd82179/raw/97d2d6a11873ffa8ca763763f7a5dd4035bcf95f/fwefnwex', 'timeout': 5}
> {'type': 5, 'url': 'https://www.proxyscan.io/download?type=socks5', 'timeout': 5}
> {'type': 5, 'url': 'https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/socks5.txt', 'timeout': 5}
> 2,941 Proxies are getting checked, this may take awhile !
> Proxy Check failed, Your network may be the problem | The target may not be available. 
> ```
> 
> **and**
> 
> ```
> # python3 start.py CFB https://exitus.me 5 972 1.txt 1000 1000
> WARNING! RPC (Request Pre Connection) is higher than 100
> WARNING! The file doesn't exist, creating files and downloading proxies.
> {'type': 5, 'url': 'https://api.proxyscrape.com/?request=displayproxies&proxytype=socks5', 'timeout': 5}
> {'type': 5, 'url': 'https://www.proxy-list.download/api/v1/get?type=socks5', 'timeout': 5}
> {'type': 5, 'url': 'https://gist.githubusercontent.com/Azuures/1e0cb7a1097c720b4ed2aa63acd82179/raw/97d2d6a11873ffa8ca763763f7a5dd4035bcf95f/fwefnwex', 'timeout': 5}
> {'type': 5, 'url': 'https://www.proxyscan.io/download?type=socks5', 'timeout': 5}
> {'type': 5, 'url': 'https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/socks5.txt', 'timeout': 5}
> 2,934 Proxies are getting checked, this may take awhile !
> Traceback (most recent call last):
>   File "start.py", line 849, in <module>
>     Proxies = ProxyManager.checkAll(Proxies, url.human_repr(), 1, threads)
>   File "start.py", line 577, in checkAll
>     with ProxyManager.poolcontext(min(len(proxie), threads)) as pool:
>   File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
>     return next(self.gen)
>   File "start.py", line 564, in poolcontext
>     pool = Pool(*args, **kwargs)
>   File "/usr/lib/python3.8/multiprocessing/context.py", line 119, in Pool
>     return Pool(processes, initializer, initargs, maxtasksperchild,
>   File "/usr/lib/python3.8/multiprocessing/pool.py", line 212, in __init__
>     self._repopulate_pool()
>   File "/usr/lib/python3.8/multiprocessing/pool.py", line 303, in _repopulate_pool
>     return self._repopulate_pool_static(self._ctx, self.Process,
>   File "/usr/lib/python3.8/multiprocessing/pool.py", line 326, in _repopulate_pool_static
>     w.start()
>   File "/usr/lib/python3.8/multiprocessing/process.py", line 121, in start
>     self._popen = self._Popen(self)
>   File "/usr/lib/python3.8/multiprocessing/context.py", line 277, in _Popen
>     return Popen(process_obj)
>   File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
>     self._launch(process_obj)
>   File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 69, in _launch
>     child_r, parent_w = os.pipe()
> OSError: [Errno 24] Too many open files
> ```
> 
> I will try fix this temporarily and issue a pull request

For the second error, use that in your terminal: **ulimit -n 65535**

**Comment by ninjutsudev** [comment]
> errors:
> 
> ```
> # python3 start.py CFB https://exitus.me 5 500 a.txt 60 900
> {'type': 5, 'url': 'https://api.proxyscrape.com/?request=displayproxies&proxytype=socks5', 'timeout': 5}
> {'type': 5, 'url': 'https://www.proxy-list.download/api/v1/get?type=socks5', 'timeout': 5}
> {'type': 5, 'url': 'https://gist.githubusercontent.com/Azuures/1e0cb7a1097c720b4ed2aa63acd82179/raw/97d2d6a11873ffa8ca763763f7a5dd4035bcf95f/fwefnwex', 'timeout': 5}
> {'type': 5, 'url': 'https://www.proxyscan.io/download?type=socks5', 'timeout': 5}
> {'type': 5, 'url': 'https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/socks5.txt', 'timeout': 5}
> 2,941 Proxies are getting checked, this may take awhile !
> Proxy Check failed, Your network may be the problem | The target may not be available. 
> ```

I have the same error... @MHProDev Any ideas?

**Comment by MHProDev** [comment]
fixed
