### ISSUE TITLE
No requests sent using CFB

### ISSUE THREAD

**Issue by SlimJUC** [MHProDev/MHDDoS#113]
there seem to be an issue with CFB

using dstat https://dstat.cc/index.php?id=CloudFlare(UAM)

requests are not being sent, all other Layer7 seem to be ok

**Comment by SlimJUC** [comment]
Any updates on this ?

L7 CFB not working

0 requests sent

**Comment by MHProDev** [comment]
use cfbuam method

**Comment by SlimJUC** [comment]
Still not working with CFBUAM

https://i.imgur.com/SQWpDoj.png


using premium proxies 

working fine with other methods like GET,,etc
