### ISSUE TITLE
How do I use it CFIP

### ISSUE THREAD

**Issue by Kaiser-DMr** [MHProDev/MHDDoS#115]
在此处添加有关功能请求的任何其他上下文或屏幕截图。
 如何使用CFIP（查找Cloudflare供电的网站的真实IP地址，我如何使用它

**Comment by bntr00t** [comment]
CFIP is not yet included in the tool.

**Comment by Kaiser-DMr** [comment]
> 。

Isn't that one of the tools

**Comment by bntr00t** [comment]
if cmd in ["CFIP", "DNS"]:
                print("Soon")
                continue
                
currently in development
