### ISSUE TITLE
BUG Report

### ISSUE THREAD

**Issue by prahaps** [MHProDev/MHDDoS#122]
Help
![image](https://user-images.githubusercontent.com/67746716/155596235-370d2431-80e4-4024-b0a2-9f5435c0d85b.png)
![image](https://user-images.githubusercontent.com/67746716/155596365-282cfb7b-6238-44ce-95c1-133eaf91b3fd.png)

**Comment by prahaps** [comment]
Doesn't work with any values

**Comment by bntr00t** [comment]
Use Bypass instead but keep on mind that proxies are not working currently

**Comment by MHProDev** [comment]
fixed in new update
