### ISSUE TITLE
BUG Report

### ISSUE THREAD

**Issue by EgorSigolaev** [MHProDev/MHDDoS#127]
**Describe the bug**
Error after starting attack. I think python script has a code bug. Method: DGB (DDoS Guard Bypass)

**Version**
Cloned last version

**Code**
python3 start.py DGB someurl.com 1 1000 socks5.txt 100 1000

**Output**
Proxy Count: 56
Traceback (most recent call last):
  File "/home/sigolaev_egor/MHDDoS/start.py", line 796, in <module>
    HttpFlood(url, method, rpc, event, uagents, referers, proxies).start()
  File "/home/sigolaev_egor/MHDDoS/start.py", line 224, in __init__
    self._raw_target = (gethostbyname(self._target.host), (self._target.port or 80))
socket.gaierror: [Errno -3] Temporary failure in name resolution

**Screenshots**
![image](https://user-images.githubusercontent.com/44138374/155840147-f5218d10-fae0-438c-b81c-12d6604199c3.png)

**Comment by bntr00t** [comment]
python3 start.py DGB http://aworkingurl.com 1 1000 socks5.txt 100 1000

Add http:// or https://
