### ISSUE TITLE
BUG Report

### ISSUE THREAD

**Issue by KasirgaRoot** [MHProDev/MHDDoS#128]
PyRoxy How To İnstall
I installed it still doesn't work I made a git clone how not to install I made the same mistake again

**Comment by MHProDev** [comment]
what error ?

**Comment by karthik558** [comment]
cd MHDDos && pip install git+https://github.com/MHProDev/PyRoxy.git --upgrade

**Comment by karthik558** [comment]
Will work fine after this

**Comment by KasirgaRoot** [comment]
@karthik558 @MHProDev 


 root@cs-1044477098383-default:/home/efemen25/MHDDoS# pip install git+https://github.com/MHProDev/PyRoxy.git --upgrade
********************************************************************************
Python 2 is deprecated. Upgrade to pip3 as soon as possible.
See https://cloud.google.com/python/docs/python2-sunset

Cloud Shell will soon default to Python 3.

To suppress this warning, create an empty ~/.cloudshell/no-pip2-warning file.
The command will automatically proceed in 5 seconds or on any key.
********************************************************************************
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Collecting git+https://github.com/MHProDev/PyRoxy.git
  Cloning https://github.com/MHProDev/PyRoxy.git to /tmp/pip-req-build-0l9cTU
  Running command git clone -q https://github.com/MHProDev/PyRoxy.git /tmp/pip-req-build-0l9cTU
ERROR: Could not find a version that satisfies the requirement maxminddb>=2.2.0 (from PyRoxy==1.0b4) (from versions: 0.1.0, 0.1.1, 0.2.0, 0.2.1, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 1.0.0, 1.1.0, 1.1.1, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.3.0, 1.4.0, 1.4.1, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 2.0.0)ERROR: No matching distribution found for maxminddb>=2.2.0 (from PyRoxy==1.0b4)

**Comment by bntr00t** [comment]
well as the error says, use Python3, soooooooooooooooo
pip3(!!!!!!!!!!!!!!!!!!!!!!!!!!!) install git etc....

**Comment by KasirgaRoot** [comment]
thank you my problem is solved @bntr00t  @MHProDev
