### ISSUE TITLE
BUG Report

### ISSUE THREAD

**Issue by Cyberb29** [MHProDev/MHDDoS#129]
I download all the requirements but cant get passed the following issue

Traceback (most recent call last):
  File "/home/whitmorekyle84/MHDDoS/start.py", line 19, in <module>
    from PyRoxy import Proxy, Tools as ProxyTools, ProxyUtiles, ProxyType, ProxyChecker
ImportError: cannot import name 'Proxy' from 'PyRoxy' (unknown location)

**Comment by s7aycool** [comment]
Same. Did you tried to install PyRoxy manually? I can't launch setup.py from PyRoxy

**Comment by bntr00t** [comment]
Pls install Python 3.9 and remove all your python packages, then just install he requirements file

**Comment by Cyberb29** [comment]
> Pls install Python 3.9 and remove all your python packages, then just install he requirements file

Thank you, problem solved.
