### ISSUE TITLE
5 Second

### ISSUE THREAD

**Issue by Timezero1** [MHProDev/MHDDoS#13]
Can Apps Bypass CloudFlare's 5 Second Protection Latency?

**Comment by MHProDev** [comment]
y method CFB

**Comment by Timezero1** [comment]
tried it, it doesn't work, could you throw off an example command, maybe I'm doing something wrong

**Comment by Timezero1** [comment]
OSError: [Errno 24] Too many open files

**Comment by MHProDev** [comment]
max thread = 1000

**Comment by Timezero1** [comment]
Thank you very much, there were a lot of streams, everything works, there is still a question, I'm testing the site, I set the limits for packets per minute, you can somehow set up sending packets per minute in the software, simulate a protection bypass

**Comment by MHProDev** [comment]
ty
