### ISSUE TITLE
pyroxy

### ISSUE THREAD

**Issue by babodai** [MHProDev/MHDDoS#132]
I am using python 3.9.1
it used to work when i added my own proxies
now i am getting error
pyroxy eror

**Comment by bntr00t** [comment]
Info. What exact error?

**Comment by babodai** [comment]
raceback (most recent call last):
File "/home/whitmorekyle84/MHDDoS/start.py", line 19, in
from PyRoxy import Proxy, Tools as ProxyTools, ProxyUtiles, ProxyType, ProxyChecker
ImportError: cannot import name 'Proxy' from 'PyRoxy' (unknown location)

**Comment by babodai** [comment]
I don't normally get this error
when i put my own proxies i get it

**Comment by bntr00t** [comment]
There might be issues with your proxies, empty spaces, IPv6, username and passwords, idk what PyRoxy supports so just try to let it get its own proxies, they work fine as long is as it even uses them

Otherwise full remove PyRoxy and reinstall requirements

**Comment by babodai** [comment]
/files/proxies/your_proxy.txt
is this way right

**Comment by bntr00t** [comment]
Yes, you can just check where it stores it by letting MHDDoS get proxies for you once

**Comment by Qvijae** [comment]
File "start.py", line 28, in <module>
    from PyRoxy import Proxy, ProxyChecker, ProxyType, ProxyUtiles
ModuleNotFoundError: No module named 'PyRoxy'
i'm too met this problem

**Comment by Qvijae** [comment]
Can u help me plz?
