### ISSUE TITLE
BUG Report

### ISSUE THREAD

**Issue by kitcoun** [MHProDev/MHDDoS#134]
![image](https://user-images.githubusercontent.com/38834202/155878993-ed4d1408-811f-4104-acf6-5967dd392fee.png)

**Comment by bntr00t** [comment]
Please remove
"https://gist.githubusercontent.com/Azuures/1e0cb7a1097c720b4ed2aa63acd82179/raw/97d2d6a11873ffa8ca763763f7a5dd4035bcf95f/fwefnwex" from the config.json or the one below it, one of them breaks it

**Comment by kitcoun** [comment]
> 请从 config.json 或它下面的一个中删除 “ [https://gist.githubusercontent.com/Azuures/1e0cb7a1097c720b4ed2aa63acd82179/raw/97d2d6a11873ffa8ca763763f7a5dd4035bcf95f/fwefnwex ”，其中一个会破坏它](https://gist.githubusercontent.com/Azuures/1e0cb7a1097c720b4ed2aa63acd82179/raw/97d2d6a11873ffa8ca763763f7a5dd4035bcf95f/fwefnwex)

Can I use socks5 password?

**Comment by bntr00t** [comment]
No.
