### ISSUE TITLE
Not working methods

### ISSUE THREAD

**Issue by bntr00t** [MHProDev/MHDDoS#137]
slow and stress arent working at all

**Comment by MHProDev** [comment]
try again with new update

**Comment by bntr00t** [comment]
slow is fixed, stress still broken

**Comment by MHProDev** [comment]
try again with stress method

**Comment by bntr00t** [comment]
> try again with stress method

50 requests on non protected target, slow does 8-10k on it

**Comment by MHProDev** [comment]
this method working for me
reinstall script and try again
![image](https://user-images.githubusercontent.com/63018646/155907835-efad220c-5095-4e46-ac31-725f1a5edbe7.png)

**Comment by bntr00t** [comment]
my fault, working :D
