### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by bntr00t** [MHProDev/MHDDoS#138]
SSL aka HTTPS websites do not work at all, checked all methods

Traceback (most recent call last):
  File "start.py", line 798, in <module>
    HttpFlood(url, method, rpc, event, uagents, referers, proxies).start()
  File "start.py", line 224, in __init__
    self._raw_target = (gethostbyname(self._target.host), (self._target.port or 80))
socket.gaierror: [Errno -2] Name or service not known

HTTP works fine but will make no request to any of the websites

**Comment by MHProDev** [comment]
try agian with need update

**Comment by bntr00t** [comment]
fixed
