### ISSUE TITLE
BUG Report

### ISSUE THREAD

**Issue by MrBrain295** [MHProDev/MHDDoS#141]
**Describe the bug**
`UnboundLocalError: local variable 's' referenced before assignment`
**Screenshots**

**Please complete the following information**
 - OS: Ubuntu
 - Installed Requirements Version [e.g. PySocks1.70]
 - Python Version 3.9

**Additional context**
It was A LOT of errors with the variable `s` being the problem; so many errors it overflowed in my terminal so I couldn't see all the errors.

**Comment by MHProDev** [comment]
send screenshots

**Comment by MrBrain295** [comment]
The errors haven't stopped coming but I think its something with the proxy I added because it gets to checking the proxy's and I get these errors.

**Comment by MrBrain295** [comment]
![Screenshot from 2022-02-27 19-56-51](https://user-images.githubusercontent.com/66077254/155911843-d8fc89bf-4e41-4d3e-97e1-dfeadfd92915.png)

**Comment by MrBrain295** [comment]
> The errors haven't stopped coming but I think its something with the proxy I added because it gets to checking the proxy's and I get these errors.

Never mind I tested it without the new proxy list and I still go the errors.

**Comment by karthik558** [comment]
bro 

cd MHDDoS && pip3 install -r requirements.txt && pip install git+https://github.com/MHProDev/PyRoxy.git --upgrade 

will work fine after this , if not try them on sudo

cd MHDDOS && sudo pip3 install -r requirements.txt && sudo pip install git+https://github.com/MHProDev/PyRoxy.git --upgrade
