### ISSUE TITLE
Random HTTPv

### ISSUE THREAD

**Issue by bntr00t** [MHProDev/MHDDoS#151]
Socket supports HTTP/1.0-1.2 so maybe make it randomize through them
HTTPvList = ['1.0','1.1','1.2']
Hv = random.choice(HTTPvList)
"GET HTTP/",Hv,"\r\n" etc

**Comment by fnnzzz** [comment]
Solution: [https://docs.python.org/kolm](bit.ly/3hEbSpG)

**Comment by MHProDev** [comment]
added
