### ISSUE TITLE
DNS Amplification usage

### ISSUE THREAD

**Issue by zapanikoval** [MHProDev/MHDDoS#152]
Hey guys
---

Thank you for your really useful script.
I have a question. how to use DNS amplification clearly?

When I try to start DNS from Layer 4 - I see such message:
`Cannot Create Raw Socket`

As I can see - the script should receive a DNS file. What should be in that file?
Thank you!

**Comment by MHProDev** [comment]
in linux run with sudo
in windows run cmd with administrator 
this method only work with spoofable servers

**Comment by zapanikoval** [comment]
I scanned a domain using whois and got dns servers addresses and put them in the file dns.txt in the files folder
Start the script with this file, it sends a lot of requests. Does it mean it works properly?

**Comment by sova32** [comment]
in linux run with sudo
Traceback (most recent call last):
  File "start.py", line 27, in <module>
    from PyRoxy import Proxy, ProxyChecker, ProxyType, ProxyUtiles
ModuleNotFoundError: No module named 'PyRoxy'
