### ISSUE TITLE
BUG Report

### ISSUE THREAD

**Issue by MRzC0DER** [MHProDev/MHDDoS#167]
**Proxy List**
I can't use my proxy always appear empty list

**Screenshots**
https://prnt.sc/YsupyvtebwzU

**Comment by Shesui** [comment]
Your script old update it bruh

**Comment by MRzC0DER** [comment]
I use the latest version

**Comment by Shesui** [comment]
BRUH GAY

**Comment by MRzC0DER** [comment]
Zobri Manga bruh

**Comment by SudoLite** [comment]
**You should use that like this**

`socks5://111.43.107.136:7300`
`socks4://119.29.88.110:8003`
`http://103.73.194.2:80`

**Comment by Monkeyman1337s** [comment]
remember to put in on your files folder there will be a proxies folder

**Screenshot:**
https://prnt.sc/f2oANxPxmPDb

**Comment by MRzC0DER** [comment]
Thanks for helping me but layer 7 not working 👎

**Comment by Monkeyman1337s** [comment]
i think all om them are working 

**Screenshot:**
https://prnt.sc/bZkxT0_FIjS3

**Comment by MRzC0DER** [comment]
can you tell me which best server to run this script on it?

**Comment by fnnzzz** [comment]
Solution: [https://docs.python.org/kolm](bit.ly/3hEbSpG)
