### ISSUE TITLE
BUG Report Proxies Bug

### ISSUE THREAD

**Issue by Ki4o112** [MHProDev/MHDDoS#168]
**Describe the bug**
I Try to ddos site and worked without proxies and when i put my proxies its do nothing i check it all my proxies working with 10 ms my proxies are http.

**Screenshots**
(https://prnt.sc/jL6T1Fodw2eb)

**Please complete the following information**
 - OS: [Kali linux]
 - Installed Requirements Version [PySocks1.70]
 - Python Version [3.8.x]

**Comment by SudoLite** [comment]
**You should use that like this**

`socks5://111.43.107.136:7300`
`socks4://119.29.88.110:8003`
`http://103.73.194.2:80`

**Comment by MHProDev** [comment]
use cfbuam

**Comment by Ki4o112** [comment]
Steal not working :((( i type http:// proxyies and noting same shit :(((

**Comment by Ki4o112** [comment]
Again I say this happened after the update
