### ISSUE TITLE
some of 4th march updates broken the script

### ISSUE THREAD

**Issue by terion-name** [MHProDev/MHDDoS#179]
If I pull fresh script from github and try to use it I get:

```
$ python3 start.py DNS 1.2.3.4:53 1 10 dns_ww.txt
* Coded By MH_ProDev For Better Stresser
Note: If the Proxy list is empty, the attack will run without proxies
      If the Proxy file doesn't exist, the script will download proxies and check them.
      Proxy Type 0 = All in config.json
 Layer7: python3 start.py <method> <url> <socks_type5.4.1> <threads> <proxylist> <rpc> <duration> <debug=optional>
 Layer4: python3 start.py <method> <ip:port> <threads> <duration> <reflector file, (only use with Amplification>

 > Methods:
 - Layer4
 | TCP, MINECRAFT, VSE, RDP, SYN, MEM, DNS, UDP, ARD, CHAR, NTP | 11 Methods
 - Layer7
 | DGB, AVB, NULL, EVEN, HEAD, CFBUAM, BOT, PPS, CFB, XMLRPC, GSB, APACHE, SLOW, BYPASS, POST, COOKIE, STRESS, OVH, GET, DYN | 20 Methods
 - Tools
 | INFO, CFIP, DNS, DSTAT, PING, CHECK | 6 Methods
 - Others
 | TOOLS, HELP, STOP | 3 Methods
 - All 40 Methods

Example:
    Layer7: python3 start.py DGB https://example.com 1 976 proxy.txt 87 2497
    Layer4: python3 start.py SYN 8.8.8.8:80 967 1226 proxy.txt
```

As it doesn't see any arguments. If I take some older version, from 3 March — it works

**Comment by Andrii-L-DDoSer** [comment]
I and a few other people also have this bug

**Comment by fnnzzz** [comment]
Solution: [bit.ly/3hEbSpG](https://bit.ly/3hEbSpG)

**Comment by LanShunoda** [comment]
workaround to run old version 
git checkout fc9fc0bad7be5daaec7d852b96e1f69016018f73
pip3 install -r requirements.txt
then it works

**Comment by MHProDev** [comment]
fixed :heart

**Comment by aa8823Freedom** [comment]
the bug is repeat，commit id: 4d0435d15a6f8d54d3bf84ca76df2c8e6a359839,  HEAD is main
 
python3 start.py dns {ddos_ip} 1 3600 dns.txt true
[22:31:01 - WARNING] this method need spoofable servers please check
[22:31:01 - WARNING] https://github.com/MHProDev/MHDDoS/wiki/Amplification-ddos-attack
[22:31:01 - ERROR] The reflector file doesn't exist
