### ISSUE TITLE
layer 4

### ISSUE THREAD

**Issue by FDeghy** [MHProDev/MHDDoS#18]
Layer 4 not work
SYN
TCP
...

**Comment by samyy5** [comment]
script کار میکنه.  برای بهتر کار کردن 
اون رو تو 
shell cloud 
باز کن.

**Comment by sajad1382** [comment]
> script کار میکنه. برای بهتر کار کردن
> اون رو تو
> shell cloud
> باز کن.

رو سیستم خودت تست کردم با وایرشارک هم دیدم "سین" که کلن ارسال نمیشد "تی سی پی" هم فکر کنم میزد
ipv4 packet
حالا دیگه نمیدونم

**Comment by MHProDev** [comment]
telegram ya discord msg bdid
