### ISSUE TITLE
BUG Report

### ISSUE THREAD

**Issue by Kaiser-DMr** [MHProDev/MHDDoS#186]
I used the seventh layer and found no effect, only for the first few seconds

 Ubuntu
 - Python 3.8.x
![截屏2022-03-05 上午11 27 12](https://user-images.githubusercontent.com/58213021/156866108-5d62b896-cb3d-4253-9755-4319ee520c30.png)
![截屏2022-03-05 上午11 29 54](https://user-images.githubusercontent.com/58213021/156866109-b10cfa10-50d9-4f12-b06a-d0b638396676.png)

**Comment by bntr00t** [comment]
It got mitigated, nothing else, also don't use dstat.cc, they are hilariously inaccurate

**Comment by SudoLite** [comment]
![Captsdfure](https://user-images.githubusercontent.com/72527182/156940568-3edc22a2-03a9-43f5-90a9-296da7a969a8.PNG)
**Working**
