### ISSUE TITLE
i can't run MHDDoS

### ISSUE THREAD

**Issue by TauzhnyanskiyArtiom** [MHProDev/MHDDoS#194]
Command: python3 start.py udp 178.248.236.20:53 10 10000 
![image](https://user-images.githubusercontent.com/28104582/156897756-42a05f66-8355-4d86-a60c-79892dc2db23.png)
This issue appeared after git pull repository.

**Comment by fnnzzz** [comment]
Solution: https://bit.ly/3hEbSpG

**Comment by LanShunoda** [comment]
workaround to run old version 
git checkout fc9fc0bad7be5daaec7d852b96e1f69016018f73
pip3 install -r requirements.txt
then it works

**Comment by MHProDev** [comment]
fixed ❤️

**Comment by tadiwosbirhanu** [comment]
can i get older version please
