### ISSUE TITLE
Bombarder dependence link gives 404

### ISSUE THREAD

**Issue by MrBrain295** [MHProDev/MHDDoS#200]
**Describe the bug**
Bombarder dependence link gives 404
**Screenshots**

**Please complete the following information**
 - OS: [e.g. Ubuntu]
 - Installed Requirements Version [e.g. PySocks1.70]
 - Python Version [e.g. 3.8.x]

**Additional context**

**Comment by MHProDev** [comment]
@PXEiYyMH8F

**Comment by MHProDev** [comment]
fixed ?
