### ISSUE TITLE
BUG Report

### ISSUE THREAD

**Issue by sykeluke** [MHProDev/MHDDoS#204]
**Describe the bug**
COMMANDO Sun 03/06/2022 18:27:39.39
C:\Users\Administrator\Desktop\hacking\ddos\MHDDoS-main>python3 start.py
Traceback (most recent call last):
  File "start.py", line 26, in <module>
    import dns.resolver
ModuleNotFoundError: No module named 'dns'

COMMANDO Sun 03/06/2022 18:29:01.98
C:\Users\Administrator\Desktop\hacking\ddos\MHDDoS-main>pip3 install dns
ERROR: Could not find a version that satisfies the requirement dns (from versions: none)
ERROR: No matching distribution found for dns
WARNING: You are using pip version 21.2.4; however, version 22.0.3 is available.
You should consider upgrading via the 'C:\Python310\python.exe -m pip install --upgrade pip' command.

COMMANDO Sun 03/06/2022 18:29:11.39
C:\Users\Administrator\Desktop\hacking\ddos\MHDDoS-main>pip3 install dnspython
Requirement already satisfied: dnspython in c:\python310\lib\site-packages (2.2.0)
WARNING: You are using pip version 21.2.4; however, version 22.0.3 is available.
You should consider upgrading via the 'C:\Python310\python.exe -m pip install --upgrade pip' command.

COMMANDO Sun 03/06/2022 18:29:39.00
C:\Users\Administrator\Desktop\hacking\ddos\MHDDoS-main>notepad

COMMANDO Sun 03/06/2022 18:30:07.16
C:\Users\Administrator\Desktop\hacking\ddos\MHDDoS-main>notepad start.py

COMMANDO Sun 03/06/2022 18:30:11.25
C:\Users\Administrator\Desktop\hacking\ddos\MHDDoS-main>

**Screenshots**

**Please complete the following information**
win 10
python 3.7

**Additional context**

**Comment by MHProDev** [comment]
https://stackoverflow.com/questions/21641696/python-dns-module-import-error
