### ISSUE TITLE
Bombardier bug

### ISSUE THREAD

**Issue by InspectorGadget1** [MHProDev/MHDDoS#209]
Unknown long flag --proxy
![image](https://user-images.githubusercontent.com/58144213/157049768-21e65f8a-23d5-41b9-826f-aab4614ecbf5.png)

**Comment by MHProDev** [comment]
[PXEiYyMH8F](https://github.com/PXEiYyMH8F)

**Comment by KursatBB** [comment]
its doing it again.

**Comment by immiProgrammer** [comment]
+1
