### ISSUE TITLE
doest work

### ISSUE THREAD

**Issue by MasterC2000** [MHProDev/MHDDoS#21]

**Comment by RomanAW** [comment]
Same doesnt work, gives errors

**Comment by RomanAW** [comment]
MHProDev, Could you help me out? I cant add you but my discord is RomanAW#6705

**Comment by xAPOC4LYPSx** [comment]
> This is the error I've been seeing when I try to run the script:
> 
> 
>     Traceback (most recent call last):
>       File "/Users/ritwickmalhotra/Desktop/MHDDoS/start.py", line 1565, in <module>
>         from scapy.layers.inet import TCP
>       File "/usr/local/lib/python3.9/site-packages/scapy/layers/inet.py", line 22, in <module>
>         from scapy.ansmachine import AnsweringMachine
>       File "/usr/local/lib/python3.9/site-packages/scapy/ansmachine.py", line 20, in <module>
>         from scapy.sendrecv import send, sniff
>       File "/usr/local/lib/python3.9/site-packages/scapy/sendrecv.py", line 61, in <module>
>         import scapy.route  # noqa: F401
>       File "/usr/local/lib/python3.9/site-packages/scapy/route.py", line 218, in <module>
>         conf.route = Route()
>       File "/usr/local/lib/python3.9/site-packages/scapy/route.py", line 37, in __init__
>         self.resync()
>       File "/usr/local/lib/python3.9/site-packages/scapy/route.py", line 45, in resync
>         from scapy.arch import read_routes
>       File "/usr/local/lib/python3.9/site-packages/scapy/arch/__init__.py", line 124, in <module>
>         from scapy.arch.bpf.supersocket import *  # noqa F403
>       File "/usr/local/lib/python3.9/site-packages/scapy/arch/bpf/supersocket.py", line 27, in <module>
>         from scapy.layers.l2 import Loopback
>       File "/usr/local/lib/python3.9/site-packages/scapy/layers/l2.py", line 17, in <module>
>         from scapy.ansmachine import AnsweringMachine
>     ImportError: cannot import name 'AnsweringMachine' from partially initialized module 'scapy.ansmachine' (most likely due to a circular import) (/usr/local/lib/python3.9/site-packages/scapy/ansmachine.py)
> ```

**Comment by MHProDev** [comment]
open the issues in scapy rpo
https://github.com/secdev/scapy/
