### ISSUE TITLE
BUG Report 

### ISSUE THREAD

**Issue by Nova-JS** [MHProDev/MHDDoS#210]
**Request to install the PyProxy module**
When the CloudShell machine starts and all modules are installed, it restarts the PyProxy installation!

**Launch stages**
git clone https://github.com/MHProDev/MHDDoS
pip3 install icmplib requests pysocks cfscrape scapy
python3 start.py post http://site.com/ 1 10000 socks5.txt 100 100
**Error**
from Proxy import Proxy, Proxy Checker, Proxy Type, Proxy Utils
ModuleNotFoundError: No module named 'PyRoxy' 

**System**
 - OS: [Cloud Shell Machine]
 - Python Version [3.9]

**Comment by SudoLite** [comment]
https://github.com/MHProDev/MHDDoS/wiki/installation

**Comment by JLU-Neal** [comment]
It is weird that I have tried pip install -r requirement.txt, but the same issue still happened.

**Comment by SudoLite** [comment]
'sudo apt-get update'

**reinstall requirements**
