### ISSUE TITLE
Proxy not loading

### ISSUE THREAD

**Issue by akashsardarop** [MHProDev/MHDDoS#212]
Os ubuntu
Python 3.9

proxy not loading and stuck ay checking proxy

**Comment by MHProDev** [comment]
send more information

**Comment by akashsardarop** [comment]
**Describe the bug**
i have tried tcp minecraft and mcbot on a server boy proxy not loading


**Please complete the following information**
 - OS: [Ubuntu 20]
 - Installed Requirements Version [ PySocks1.70]
 - Python Version [ 3.9]

![Capture](https://user-images.githubusercontent.com/73843791/157165700-53c968ad-7abc-4a62-9f76-e99d8c648645.PNG)

**Comment by SudoLite** [comment]
**Your proxies already loaded and attack started**
**I guess you need debug mode**

**Comment by akashsardarop** [comment]
> **Your proxies already loaded and attack started**
> **I guess you need debug mode**

I open the server console but could not see any connection 
Also how to turn on debug?

**Comment by SudoLite** [comment]
To turn on debugging mode
Add the end of the line "true"

**Comment by akashsardarop** [comment]
@MHProDev 
Can you please add more examples commands

**Comment by SudoLite** [comment]
https://github.com/MHProDev/MHDDoS/wiki
