### ISSUE TITLE
proxies not loading

### ISSUE THREAD

**Issue by Daddy666291** [MHProDev/MHDDoS#213]
I installed all the libraries, I use kali linux through a virtual machine, I run python3 start.py from the beginning and the problem is "cannot import name SOCKS4 from socks"
then with the parameters and everything is the same, before this was not the case, after the update such a problem began to arise

**Comment by Daddy666291** [comment]
here is the screenshot https://imgur.com/a/3Ry9pq7

**Comment by MHProDev** [comment]
u runned pip install socks ?

**Comment by MHProDev** [comment]
or with requirements.txt

**Comment by Daddy666291** [comment]
no, I also have it installed, here is a screen of what is installed, I used this utility earlier, it was fine, after the update it no longer works.
https://imgur.com/a/oAGT2FH
