### ISSUE TITLE
BUG Report

### ISSUE THREAD

**Issue by JLU-Neal** [MHProDev/MHDDoS#215]
**Describe the bug**
ModuleNotFoundError: No module named 'PyRoxy'
Actually, I have found a similar issue proposed before, and I tried pip install -r requirement.txt, but errors still happened.

**Please complete the following information**
 - OS: [e.g. Ubuntu]
 - Python Version [e.g. 3.9.7]

**Comment by Shesui** [comment]
sudo pip3 install -r requirement.txt

**Comment by JLU-Neal** [comment]
> sudo pip3 install -r requirement.txt

Cool it is solved

**Comment by saber-dym** [comment]
Why did I python install that package, but still report the error without that package
