### ISSUE TITLE
I can't get the method to work

### ISSUE THREAD

**Issue by Elforget** [MHProDev/MHDDoS#223]
Started with sudo as I was told.

Got an error that I didn't install PyRoxy, but I did everything according to the instructions.

What is the problem, maybe I don't understand, because I'm new to Linux.

I would be grateful for help, or better yet, please send me a command that will work without errors. 

**Thank you.**
![image](https://user-images.githubusercontent.com/45536046/157781754-b5fafb36-4194-4ebb-85d0-ef11a26da687.png)

**Comment by cold9999** [comment]
You should run the script as Normal User
If you must run the script as ROOT, execute this command in Directory "sudo pip3 install -r requirements.txt"
