### ISSUE TITLE
YouTube Tutorial in Readme isn't available

### ISSUE THREAD

**Issue by CaiqueCoelho** [MHProDev/MHDDoS#225]
**Describe the bug**
The tutorial video at Youtube isn't available

**Screenshots**
![Captura de Tela 2022-03-11 às 10 42 21](https://user-images.githubusercontent.com/29831309/157879162-afbd85ec-63b8-4f16-8991-5293c379d82d.png)

**Additional context**
Link: https://www.youtube.com/watch?v=mZilAOkLKK8

**Comment by SudoLite** [comment]
**Fixed**
