### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by sova32** [MHProDev/MHDDoS#226]
please add hint about optimal requests for one thread in one time period. How to calculate optimal parametrs
wery need! please/ I am from Ukraine. We must fight with russian fashism more effective. Sorry for my english! Can you give any good tools and helpfull information& Please help!
Slava Ukraine!

**Comment by realn0whereman** [comment]
https://t.me/c/1627443142/161
Брат, пиши тут

Maintainers,
We can close this issue

**Comment by Xoosz** [comment]
can't access your telegram

**Comment by sova32** [comment]
realn0whereman Брат. Я от туда и пришел :-) Спасибо! Вроде разобрался. 
Подскажи какими методами эффективней всего атаковать. Я хочу написать микроинструкцию с примерами для поддержки новичков. Пошо я смотрю даже школьники атаки пытаются вести и свои хакерские каналы создают :-)

**Comment by realn0whereman** [comment]
Давай как то не на гитхабе? И все вместе удалим эту всю переписку ?

**Comment by sova32** [comment]
простите. полностью согласен. если можете - удалите.

сб, 12 марта 2022, 3:18 PM realn0whereman ***@***.***>:

**Comment by Xoosz** [comment]
what
