### ISSUE TITLE
BUG Report

### ISSUE THREAD

**Issue by alwaes** [MHProDev/MHDDoS#229]
when I run start.py pops up 
Traceback (most recent call last):
  File "/home/fefefes/MHDDoS/start.py", line 28, in <module>
    from PyRoxy import Proxy, ProxyChecker, ProxyType, ProxyUtiles
ImportError: cannot import name 'Proxy' from 'PyRoxy' (unknown location)

**Comment by akashsardarop** [comment]
sudo pip3 install pyroxy
use this command

**Comment by alwaes** [comment]
did not help
