### ISSUE TITLE
Proxy are not getting loaded BUG

### ISSUE THREAD

**Issue by akashsardarop** [MHProDev/MHDDoS#230]
**Describe the bug**
stuck at proxy are getting checked 
proxy not loaded after 4 hours also

**Screenshots**
screenshot given

**Please complete the following information**
 - OS: [ Ubuntu 20 ]
 - Installed Requirements Version [PySocks1.70]
 - Python Version [3.8]

**Additional context**
i waited for 4 hours but still proxy not loaded
please fix
![image](https://user-images.githubusercontent.com/73843791/158015036-83f59daa-142e-4adf-a075-51f174a8f3ae.png)

**Comment by Shesui** [comment]
Don't use sudo stupid guy
