### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Shesui** [MHProDev/MHDDoS#236]
To optimize the script since python is not the fastest, divide the attack methods into files not in one start py just in one call the other files to attack

**Comment by Condadon99** [comment]
To clarify: when i run the script from my machine, on an average it generates a power of about 2.5Gbps to 3Gbps. If i needed let's say an attack of 25Gbps. I just run the script in 10 different windows? That doesn't sound right as the size of attack is still limited to my internet bandwidth- max traffic/upload speed. Is there any other way to lift the size of attacks? Thanks
