### ISSUE TITLE
GitHub Pages issues

### ISSUE THREAD

**Issue by MrBrain295** [MHProDev/MHDDoS#241]
**Describe the bug**
The GitHub pages for this repo aren’t looking how they should.
**Screenshots**

**Please complete the following information**
 - OS: [e.g. Ubuntu]
 - Installed Requirements Version [e.g. PySocks1.70]
 - Python Version [e.g. 3.8.x]

**Additional context**

**Comment by SudoLite** [comment]
**It changed. Thank you for reminding me**

**Comment by MrBrain295** [comment]
@SudoLite it is still not fixed.
