### ISSUE TITLE
Improve

### ISSUE THREAD

**Issue by Xoosz** [MHProDev/MHDDoS#245]
Improve all proxy

**Comment by SudoLite** [comment]
what do you mean? Write any idea for us

**Comment by Xoosz** [comment]
Improve proxy

![image](https://user-images.githubusercontent.com/96109135/158358777-a9736d9b-e890-4e7e-bcfa-1ce6f620c0a8.png)

**Comment by Xoosz** [comment]
Socks5 
![image](https://user-images.githubusercontent.com/96109135/159655931-4c411dfe-caa7-4ecb-bc5a-0a1c70b7a0d1.png)
