### ISSUE TITLE
Russian language pack

### ISSUE THREAD

**Issue by sergiomarotco** [MHProDev/MHDDoS#247]
I want help to translate interface on Russian language. Say what files i need to edit, and i can make a pull request

**Comment by sergiomarotco** [comment]
@Shesui как понял украинцы пользуются для атаки на РФ, им будет полезен хотя бы русский язык

**Comment by Shesui** [comment]
Так просто седлай гайд на Ютубе и выложи его

**Comment by sergiomarotco** [comment]
Не проще

**Comment by webvitalii** [comment]
@sergiomarotco @Shesui 
Думаю для украинцев русский язьік не нужен. Много русско-язьічньіх уже перешли на украинский. Слово "русский" за две недели стал синонимом "бубонной чумьі".  А украинские IT-шники нормально английский понимают.

Если хотите помочь Украине, то **наведите порядок у себя в стране**. Из-за того, что вьі там ничего не делали последние 30 лет, то ваша раковая опухоль дала метастазьі. Русская армия уже убила тьісячи мирньіх людей и разрушила десятки городов.

Если ничего не будете делать, то вам самим скоро **жрать нечего будет**!

**Comment by webvitalii** [comment]
@sergiomarotco @Shesui 
Ну что, как там жизнь крепостньіх холопов во времена правлення царя-батюшки?
Или царь все еще хороший, а вот бояре прохие.

Вам, русским, еще сколько нужно веков, чтобьі уже самим начать себе президента вьібирать? Сто все еще при царе живете.

А всем другим народам внутри России еще сколько нужно веков, чтобьі наконец-то вьійти из "тюрмьі народов" и начать создавать свою страну со своим язьіком, культурой, традициями?
