### ISSUE TITLE
Optimization

### ISSUE THREAD

**Issue by Shesui** [MHProDev/MHDDoS#250]
Hi favorite developer script. My idea is to separate files with ddos methods sounds incomprehensible, but I will try to explain. We have start.py but python is pretty slow and will have a hard time with so many imports and lines of code. So you could make start.py like a collection of other files to include scripts from other files like

cfb.py -->
bypass.py -->
get.py --> 
--> start.py by simply calling them all in one file and splitting the methods into separate files.

**Comment by MrBrain295** [comment]
Or maybe to go as far as a base script a proxy script and one for each attack (in a separate folder).

**Comment by Shesui** [comment]
> 

if you don’t understand what I want to say, then it’s not my problem, don’t show off here and make a moron out of yourself
