### ISSUE TITLE
No proxy

### ISSUE THREAD

**Issue by Plopptheblacke** [MHProDev/MHDDoS#257]
### Which section is this feature request for?

L7 (DDoS Attack Layer 7)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Nope

### Describe the solution you'd like

Make it so we can send attacks without the use if proxys

### Additional context

Please

**Comment by SudoLite** [comment]
You can already send attacks without using a proxy

Just create an empty file in the proxy folder

**Comment by Plopptheblacke** [comment]
> You can already send attacks without using a proxy
> 
> Just create an empty file in the proxy folder
> 
> **Do you have a new idea?**

Ive t

> You can already send attacks without using a proxy
> 
> Just create an empty file in the proxy folder
> 
> **Do you have a new idea?**

There is no proxy file? No folder

**Comment by SudoLite** [comment]
i know 
create in  `proxies` folder
