### ISSUE TITLE
[BUG Report]: Proxy docs not correct, please fix wasted hours on bad docs

### ISSUE THREAD

**Issue by neanon4096** [MHProDev/MHDDoS#260]
### Version

2.4 (Default)

### Which section is the problem?

L7 (DDoS Attack Layer 7)

### Please complete the following information

```true
<Type>://<Host>:<Port>@<User=Optional>:<Password=Optional>

on this page https://github.com/MHProDev/MHDDoS/wiki/Proxy-Files


The '@' should be a ':'

https://github.com/MHProDev/PyRoxy/blob/master/PyRoxy/__init__.py#L68
```

### What happened (Describe the bug) ?

Bad docs

### Screenshots

https://i.imgur.com/wl7VRUR.jpeg

### Please provide a link to a minimal reproduction of the bug

docs

### Relevant log output

```shell
docs
```

**Comment by neanon4096** [comment]
Would be nice to have an example with user/pass

**Comment by SudoLite** [comment]
Thank you
