### ISSUE TITLE
Cannot Create Raw Socket

### ISSUE THREAD

**Issue by TonyLCH** [MHProDev/MHDDoS#269]
### Version

2.4 (Default)

### Which section is the problem?

L4 (DDoS Attack Layer 4)

### Please complete the following information

```true
- OS:windows subsystem for linux debian
- Python Version 3.9.2
```

### What happened (Describe the bug) ?

Cannot Create Raw Socket appears when using L4 Amp
![Screenshot (14)](https://user-images.githubusercontent.com/37832991/158952359-8829d449-728e-4c46-ae6a-6ea27b4a8b4e.png)

### Screenshots

https://www.hkcls-network.gq/Screenshot(14).png

**Comment by Shesui** [comment]
Don't use sudo in command

**Comment by TonyLCH** [comment]
Still can't run in windows subsystem for linux,How to fix
![Screenshot (15)](https://user-images.githubusercontent.com/37832991/158963356-03d9f2f9-78c1-4cf4-8772-a9a7e2f8cd8e.png)

**Comment by MHProDev** [comment]
run cmd as administrator
