### ISSUE TITLE
[BUG Report]: error help

### ISSUE THREAD

**Issue by ninjabys** [MHProDev/MHDDoS#275]
### Version

2.4 (Default)

### Which section is the problem?

Script Base

### Please complete the following information

```true
- OS: [e.g. Ubuntu]
- Installed Requirements Version [e.g. PySocks1.70]
- Python Version [e.g. 3.8.x]

i got error :
 from PyRoxy import Proxy, ProxyChecker, ProxyType, ProxyUtiles
ModuleNotFoundError: No module named 'PyRoxy' 

how i solution that??
```

### What happened (Describe the bug) ?

A bug happened! 

### Screenshots

https://ibb.co/pR5vNYr

**Comment by andress134** [comment]
> 

Module is missing
take a look here : https://github.com/MHProDev/PyRoxy

**Comment by SudoLite** [comment]
https://github.com/MHProDev/MHDDoS/wiki/installation

**Comment by grivas** [comment]
I am having the same problem, I followed the installation guide.

**Comment by allahscodewarrior** [comment]
> > 
> 
> Module is missing take a look here : https://github.com/MHProDev/PyRoxy

still doesnt work.
ERROR: Could not find a version that satisfies the requirement maxminddb>=2.2.0 (from PyRoxy==1.0b5) (from versions: 0.1.0, 0.1.1, 0.2.0, 0.2.1, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 1.0.0, 1.1.0, 1.1.1, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.3.0, 1.4.0, 1.4.1, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 2.0.0)
ERROR: No matching distribution found for maxminddb>=2.2.0 (from PyRoxy==1.0b5)

**Comment by neckinn** [comment]
I still have this problem

**Comment by ShonenNoSeishin** [comment]
I don't really know why but personnaly I resolved this by installing the two missing packages separately with sudo :
```
sudo pip install "pyroxy @ git+https://github.com/MatrixTM/PyRoxy.git"
sudo pip install "cloudscraper"

``` 

and after i can run an attack (with sudo too) : 

```
sudo python3 start.py ICMP 172.16.32.2:80 300 3600
``` 

Regards ;) ,
