### ISSUE TITLE
Use secrets instead of random

### ISSUE THREAD

**Issue by MrBrain295** [MHProDev/MHDDoS#278]
### Which section is this feature request for?

Script Base

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

The secrets library makes more secure random numbers then the random library

### Describe the solution you'd like

Migrate away from random to secrets.

**Comment by MHProDev** [comment]
https://github.com/MHProDev/MHDDoS/commit/4a3f7ad14ea3e2c7ce99eef33492f442255e68aa
