### ISSUE TITLE
[BUG Report]:

### ISSUE THREAD

**Issue by Qvijae** [MHProDev/MHDDoS#279]
### Version

2.4 (Default)

### Which section is the problem?

Script Base

### Please complete the following information

```true
- OS: [e.g. Ubuntu]
- Installed Requirements Version [e.g. PySocks1.70]
- Python Version [e.g. 3.8.x]

File "start.py", line 28, in <module>
    from PyRoxy import Proxy, ProxyChecker, ProxyType, ProxyUtiles
ImportError: cannot import name 'Proxy' from 'PyRoxy' (unknown location)
```

### What happened (Describe the bug) ?

A bug happened!

### Screenshots

https://ibb.co/pR5vNYr

### Relevant log output

```shell
File "start.py", line 28, in <module>
    from PyRoxy import Proxy, ProxyChecker, ProxyType, ProxyUtiles
ImportError: cannot import name 'Proxy' from 'PyRoxy' (unknown location)
```

**Comment by MHProDev** [comment]
update pyroxy

**Comment by MHProDev** [comment]
install pyroxy with git
pip install git+https://github.com/MHProDev/PyRoxy.git

**Comment by Kyurem102** [comment]
Having same issue. I think the content is missing when I attempt to run that exact command

**Comment by Noise13po** [comment]
same errors :/

**Comment by MHProDev** [comment]
please install pyroxy with 
```console
pip install git+https://github.com/MHProDev/PyRoxy.git
```
instead of
```console
pip install pyroxy
```

**Comment by alexnest-ua** [comment]
> same errors :/

You forgot to install the newest pip...

So for MHDDoS will be correct this one algorithm:
```shell
sudo apt update -y
sudo apt install python3 -y
sudo apt upgrade python3 -y
sudo apt install python3-pip -y
sudo apt upgrade python3-pip -y
sudo -H pip3 install --upgrade pip
cd ~                (or your directory with MHDDoS)
sudo rm -r MHDDoS
git clone https://github.com/MHProDev/MHDDoS.git
cd MHDDoS
sudo pip3 install -r requirements.txt
sudo python3 start.py get https://example.com 5 1000 socks5.txt 100 100
```

**Comment by MountainsBerg** [comment]
> please install pyroxy with
> 
> ```
> pip install git+https://github.com/MHProDev/PyRoxy.git
> ```
> 
> instead of
> 
> ```
> pip install pyroxy
> ```



> please install pyroxy with
> 
> ```
> pip install git+https://github.com/MHProDev/PyRoxy.git
> ```
> 
> instead of
> 
> ```
> pip install pyroxy
> ```

deal
