### ISSUE TITLE
Your discord on your readme doesn't work

### ISSUE THREAD

**Issue by JamieGrimwood** [MHProDev/MHDDoS#28]
Please update your discord on your readme, I want to contact you.

**Comment by andress134** [comment]
> Please update your discord on your readme, I want to contact you.

this are a shit script.
Man use public libs and public functions
look on pastebin ''cfbypass'' will found py version of the ddos script ''cfbypass'' and also ''cc.py'' him just copied functions and create all in one. just the panel made by him (maybe)
so all ''bypass'' methods are patched, using cfscrape etc (oupdated libs)

Real function and  ddos script ''cfbypass'' is made by user Node  ( Node#6354 ) . You can found him on hf or nulled and u will see him posted it 2 years ago, same script and function used on this ''mhddos'' for cfbypass etc

Just copy paste one line of every function from this script, paste it on gogle and u will found real scripts that used this func, very old scripts
So the owner of mhddos just use public func, and create the panel all in one, also copied from  github real name is ''jmddos'' posted 2 years ago
