### ISSUE TITLE
[BUG Report]: ImportError: cannot import name 'Callable' from 'collections' 

### ISSUE THREAD

**Issue by korenhskoh** [MHProDev/MHDDoS#282]
### Version

2.4 (Default)

### Which section is the problem?

Script Base

### Please complete the following information

```true
- OS: [e.g. window]
- Installed Requirements Version [e.g. PySocks1.70]
- Python Version [e.g. 3.10.0]
```

### What happened (Describe the bug) ?

 from socks import socksocket, SOCKS4, SOCKS5, HTTP
  File "C:\Users\fusiongk\AppData\Local\Programs\Python\Python310\lib\site-packages\socks.py", line 61, in <module>
    from collections import Callable
**ImportError: cannot import name 'Callable' from 'collections'** (C:\Users\fusiongk\AppData\Local\Programs\Python\Python310\lib\collections\__init__.py)

There is an error while i running the script.Any advise can help ?
![bug](https://user-images.githubusercontent.com/56794226/159155812-41798815-5535-42a5-8107-445d7a037201.png)

### Screenshots

https://imgur.com/a/icw5MmY

**Comment by MHProDev** [comment]
fixed in last commit
