### ISSUE TITLE
SyntaxError AGAIN THE SAME

### ISSUE THREAD

**Issue by alexnest-ua** [MHProDev/MHDDoS#287]
Traceback (most recent call last):
  File "runner.py", line 12, in <module>
    from MHDDoS.start import ProxyManager, logger
  File "/home/azureuser/mhddos_proxy/MHDDoS/start.py", line 27, in <module>
    from PyRoxy import Proxy, ProxyChecker, ProxyType, ProxyUtiles
  File "/usr/local/lib/python3.8/dist-packages/PyRoxy/__init__.py", line 13, in <module>
    from PyRoxy import GeoIP, Tools
  File "/usr/local/lib/python3.8/dist-packages/PyRoxy/Tools/__init__.py", line 18
    rand_char: Callable[[int], chr] = lambda length=16: chr(Random.rand_int(0, 1000)) for _ in range(length)
                                                                                      ^
SyntaxError: invalid syntax

Because of last commit in PyProxy: https://github.com/MHProDev/PyRoxy/commit/ffecf3fb67306172e6e0444e851093a059bf12c1

**Comment by alexnest-ua** [comment]
Because of last commit in PyProxy: https://github.com/MHProDev/PyRoxy/commit/ffecf3fb67306172e6e0444e851093a059bf12c1

**Comment by ninjutsudev** [comment]
I've already added a merging request for the PyRoxy solving that problem.

https://github.com/MHProDev/PyRoxy/pull/12

**Comment by alexnest-ua** [comment]
And how to make this work with MHDDoS ?

**Comment by ninjutsudev** [comment]
> And how to make this work with MHDDoS ? In the original repo is still error code, so it isn`t work with MHDDoS right now

https://github.com/MHProDev/PyRoxy/pull/12#issuecomment-1073308034

**Comment by cmderx** [comment]
running script is syntax error, help please (start.py)

**Comment by ninjutsudev** [comment]
> running script is syntax error, help please (start.py)

Read my first comment in this thread...

**Comment by garywu520** [comment]
Waiting fix...

**Comment by dave9123** [comment]
Use python3 start.py (your choice) instead of py or python as it might not work.

**Comment by ninjutsudev** [comment]
> Use python3 start.py (your choice) instead of py or python as it might not work.

That is not the source of the problem. Update PyRoxy, the problem was solved yesterday by me.

**Comment by ninjutsudev** [comment]
> Use python3 start.py (your choice) instead of py or python as it might not work.

That is not the source of the problem. Update PyRoxy, the problem was solved yesterday by me.

**Comment by MHProDev** [comment]
fixed in last commit

**Comment by alexnest-ua** [comment]
How to update it? I run requirements from MHDDoS, and this error occur again and again

**Comment by RossLux** [comment]
> How to update it? I run requirements from MHDDoS, and this error occur again and again

`pip install --upgrade --force-reinstall -r requirements.txt`

**Comment by ninjutsudev** [comment]
> > How to update it? I run requirements from MHDDoS, and this error occur again and again
> 
> `pip install --upgrade --force-reinstall -r requirements.txt`

Lately people come to GitHub to install things without even knowing what they are for. The comment you replied to is an example.

**Comment by alexnest-ua** [comment]
> > How to update it? I run requirements from MHDDoS, and this error occur again and again
> 
> `pip install --upgrade --force-reinstall -r requirements.txt`

I ran it after sudo ```shell git pull origin main ```, but that didn`t work anyway, only now it works.

**Comment by dave9123** [comment]
Probably do 
`sudo apt install python3`
`pip install -r requirements.txt`
`python3 start.py`
It works for me

**Comment by alexnest-ua** [comment]
> Probably do `sudo apt install python3` `pip install -r requirements.txt` `python3 start.py` It works for me

It worked 4 days ago, the full list of commands will be:

`sudo apt install python3 -y`
`sudo apt upgrade python3 -y`
`sudo apt install python3-pip -y`
`sudo apt upgrade python3-pip -y`
`sudo -H pip3 install --upgrade pip`

#Install latest version of MHDDoS
`cd ~`
`sudo rm -r MHDDoS`
`git clone https://github.com/MHProDev/MHDDoS.git`
`cd MHDDoS`
`sudo pip3 install -r requirements.txt`
`sudo python3 start.py ...`
