### ISSUE TITLE
SyntaxError 3d time with MHDDoS

### ISSUE THREAD

**Issue by alexnest-ua** [MHProDev/MHDDoS#291]
![image](https://user-images.githubusercontent.com/74729549/159267536-f0372658-c4c3-4210-bc00-ff649964283e.png)

root@ubuntu-switzeland:~/mhddos_proxy/MHDDoS# python3 start.py get https://sberbank.ru 5 1000 socks5.txt 100 100
Traceback (most recent call last):
  File "start.py", line 27, in <module>
    from PyRoxy import Proxy, ProxyChecker, ProxyType, ProxyUtiles
  File "/usr/local/lib/python3.8/dist-packages/PyRoxy/__init__.py", line 13, in <module>
    from PyRoxy import GeoIP, Tools
  File "/usr/local/lib/python3.8/dist-packages/PyRoxy/Tools/__init__.py", line 18
    rand_char: Callable[[int], chr] = lambda length=16: chr(Random.rand_int(0, 1000)) for _ in range(length)
                                                                                      ^
SyntaxError: invalid syntax

This error not because of PyProxy directly now, but because of not rebuilted MHDDoS

I have the latest version:
![image](https://user-images.githubusercontent.com/74729549/159268445-1de5683b-30d8-4868-a8c3-004c16ada4d9.png)

root@ubuntu-switzeland:~/mhddos_proxy/MHDDoS# git pull origin main
From https://github.com/MHProDev/MHDDoS
 * branch            main       -> FETCH_HEAD
Already up to date.

**Comment by cmderx** [comment]
assign dev to this

**Comment by alexnest-ua** [comment]
It seems that some (or all) of the MHProDev's developers are from Russia, because very often they started doing the same problem with one fucking bracket, and now they haven't solved the problem for almost a day
