### ISSUE TITLE
51 methods, but in fact 4 ?

### ISSUE THREAD

**Issue by alexnest-ua** [MHProDev/MHDDoS#296]
I'm new in programming and I just don't understand these lines: https://github.com/MHProDev/MHDDoS/blob/b22865fe5f3e78fe82f632d10b478b4ddf551a78/start.py#L625

Сan someone, please, explain to me why there are 51 methods in the description, but in fact there are only 4 of them?

I started to explore the code because after two weeks of using MHDDoS,  I noticed that not any method of bypassing DDoS protection doesn`t gives the desired result.

**Comment by bntr00t** [comment]
This is false, you can see different request methods like Get and Post, the rest are bypassing ways, or raw stuff, what you see is just the if statement for the HTTP method

**Comment by alexnest-ua** [comment]
> This is false, you can see different request methods like Get and Post, the rest are bypassing ways, or raw stuff, what you see is just the if statement for the HTTP method

But just check the def functions with different methods, they are all either completely similar or not much different

**Comment by bntr00t** [comment]
That might be, but just a small change can do a lot in case of protections

**Comment by GeekHamza1** [comment]
/root/MHDDoS/bypass': [Errno 2] No such file or directory

can you add declared methods please ?
