### ISSUE TITLE
[BUG Report]: fix bandit test

### ISSUE THREAD

**Issue by MrBrain295** [MHProDev/MHDDoS#298]
### Version

2.4 (Default)

### Which section is the problem?

Other

### Please complete the following information

```true
- OS: [e.g. Ubuntu]
- Installed Requirements Version [e.g. PySocks1.70]
- Python Version [e.g. 3.8.x]
```

### What happened (Describe the bug) ?

The build fails because of a bug in the bandit.yml file.

### Screenshots

n/a

### Please provide a link to a minimal reproduction of the bug

n/a

### Relevant log output

```shell
n/a
```

### Additional context

n/a

### Your code

```true
n/a
```

**Comment by SudoLite** [comment]
deleted
