### ISSUE TITLE
How do I add my own proxies with authorization?

### ISSUE THREAD

**Issue by safeandroidtv** [MHProDev/MHDDoS#30]
Hi, tell me how to add your proxy list with authorization (user and password)?, thank you)

**Comment by inplex-sys** [comment]
i think it's not possible because off the scraping process who clear the proxies file, it didn't append it

**Comment by Adiru3** [comment]
> Hi, tell me how to add your proxy list with authorization (user and password)?, thank you)

You can replace a piece of code from 1301 line, after which it will not download proxies again, and upload your proxies to files / proxys / name.txt

    print("downloading {}'s proxy plz wait".format(socktyper))
    print ("Number Of Socks%s's Proxies: %s" %(choice,len(proxies)))
    check_list(out_file)
    ans = str(input("Want to download a proxy?(y/n, defualt=y):"))
    print("Please wait, proxies are being downloaded")
    if ans == "":
        ans = "y"
    if ans == "y":
            print ("Downloading {}'s Please Wait".format(socktyper))
            downloadsocks(choice)
            proxies = open(str(out_file)).readlines()
            check_list(out_file)
            check_socks(ms)
