### ISSUE TITLE
I want to request feature Random Query String Attack and ability to modify http headers

### ISSUE THREAD

**Issue by longcharmroeun** [MHProDev/MHDDoS#302]
### Which section is this feature request for?

L7 (DDoS Attack Layer 7)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

some site are using cloudflare full cache so when ddos most of your method aren't working and some site are using host header to check domain or IP so even if i have target IP it will redirect to their domain.

### Describe the solution you'd like

i want you to add feature that can random query string to bypass cloudflare full cahe and ability to modify http headers

**Comment by MHProDev** [comment]
method gsb
