### ISSUE TITLE
PyRoxy requirement missing from requirements folder

### ISSUE THREAD

**Issue by Sixaiti** [MHProDev/MHDDoS#303]
### Version

2.4 (Default)

### Which section is the problem?

Other

### Please complete the following information

```true
- OS: [e.g. Ubuntu]
- Installed Requirements Version [e.g. PySocks1.70]
- Python Version [e.g. 3.8.x]
```

### What happened (Describe the bug) ?

Missing PyRoxy requirement from the requirements.txt file
please update for future! - for other people seeing, open cmd and type
'pip install PyRoxy' without quotations for it to work!

### Screenshots

imgur.com/7digits

### Your code

```true
Missing PyRoxy requirement from the requirements.txt file
please update for future! - for other people seeing, open cmd and type
'pip install PyRoxy' without quotations for it to work!
```

**Comment by Melih-GMC2** [comment]
try to use python3.9 and pip3.9

**Comment by Professor500** [comment]
> ### Version
> 2.4 (Default)
> 
> ### Which section is the problem?
> Other
> 
> ### Please complete the following information
> ```
> - OS: [e.g. Ubuntu]
> - Installed Requirements Version [e.g. PySocks1.70]
> - Python Version [e.g. 3.8.x]
> ```
> 
> ### What happened (Describe the bug) ?
> Missing PyRoxy requirement from the requirements.txt file please update for future! - for other people seeing, open cmd and type 'pip install PyRoxy' without quotations for it to work!
> 
> ### Screenshots
> imgur.com/7digits
> 
> ### Please provide a link to a minimal reproduction of the bug
> _No response_
> 
> ### Relevant log output
> _No response_
> 
> ### Additional context
> _No response_
> 
> ### Your code
> ```
> Missing PyRoxy requirement from the requirements.txt file
> please update for future! - for other people seeing, open cmd and type
> 'pip install PyRoxy' without quotations for it to work!
> ```

pip install -r requirements.txt
