### ISSUE TITLE
Issue with deleting proxy from folder.

### ISSUE THREAD

**Issue by wirelessconnection** [MHProDev/MHDDoS#36]
This function, as I understand it, should check the proxy for valid and removes all invalid ones. And if I don't want these proxies to be checked? I have my own valid proxies, and this function just removes most of them. If I try to remove this function from the code, the script hangs and something strange happens to it (the console does not respond and it cannot be turned off, and the attack continues).

**Comment by Adiru3** [comment]
Go to 1301 line and note:

    print("downloading {}'s proxy plz wait".format(socktyper))
    print ("Number Of Socks%s's Proxies: %s" %(choice,len(proxies)))
    check_list(out_file)
    ans = str(input("Want to download a proxy?(y/n, defualt=y):"))
    print("Please wait, proxies are being downloaded")
    if ans == "":
        ans = "y"
    if ans == "y":
            print ("Downloading {}'s Please Wait".format(socktyper))
            downloadsocks(choice)
            proxies = open(str(out_file)).readlines()
            check_list(out_file)
            check_sock
