### ISSUE TITLE
ImportError: cannot import name 'AnsweringMachine' from partially initialized module 'scapy.ansmachine' (most likely due to a circular import) (/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/scapy/ansmachine.py)

### ISSUE THREAD

**Issue by lexuanquynh** [MHProDev/MHDDoS#39]
ImportError: cannot import name 'AnsweringMachine' from partially initialized module 'scapy.ansmachine' (most likely due to a circular import) (/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/scapy/ansmachine.py)

**Comment by MHProDev** [comment]
please open this issues in scapy git
