### ISSUE TITLE
socks type not found

### ISSUE THREAD

**Issue by skycosth** [MHProDev/MHDDoS#4]
socks type not found

**Comment by MHProDev** [comment]
python3 start.py bypass https://example.com 5 1000 socks5.txt 100 100
python3 start.py <method> <url> <proxytype> <thread> <proxyfile>  <multiple> <time>

sockstypes = 5, 4, 1
5 = socks5
4 = socks4
1 = http

**Comment by skycosth** [comment]
ok tkx you

**Comment by skycosth** [comment]
Request an example ddos ​​l4 command pls

**Comment by MHProDev** [comment]
python3 start.py udp http://8.8.8.8:80 5 1000 socks5.txt 100 100

**Comment by MHProDev** [comment]
proxy is fake
python3 start.py <method> http://<ip>:<port> 5 <thread> socks5.txt <multi> <time>
