### ISSUE TITLE
ModuleNotFoundError: No module named 'PyRoxy'

### ISSUE THREAD

**Issue by 2331892928** [MHProDev/MHDDoS#400]
### Which section is this feature request for?

Script Base

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I have already installed PyRoxy but this is still prompted

### Describe the solution you'd like

normal

**Comment by SkinAir** [comment]
I have the same problem

**Comment by SkinAir** [comment]
I have the same problem

**Comment by SkinAir** [comment]
![image](https://user-images.githubusercontent.com/71880910/187835007-82c0a546-3ad1-4164-bdc1-4873e3e8f91f.png)


> 我也有同样的问题

![image](https://user-images.githubusercontent.com/71880910/187835025-3c15a414-6d2d-4a74-bfe7-0bff62e76982.png)

**Comment by quanmanss11** [comment]
xd

**Comment by quanmanss11** [comment]
i lost my last my brain cells (use python BRUH.py command)

**Comment by quanmanss11** [comment]
dont use python3

**Comment by quanmanss11** [comment]
are you stupid 😭😭😭😭😭😭

**Comment by cjt-onion** [comment]
Do the following: Install pyroxy using the command line, pip install PyRoxy, then create in the /Lib folder where you have installed your python a PyRoxy folder with the structure of https://github.com/MatrixTM/PyRoxy/tree/master/PyRoxy Use the same files. Best regards..
