### ISSUE TITLE
i think that someone stole your code

### ISSUE THREAD

**Issue by Bechebeche999** [MHProDev/MHDDoS#43]
https://github.com/the-deepnet/ddos
see this

**Comment by slpkbt** [comment]
it looks like this guy really stole the idea and code 1 in 1

**Comment by Bechebeche999** [comment]
> it looks like this guy really stole the idea and code 1 in 1

I Agree he is skid the main topic where is MHPRODEV

**Comment by PC1266** [comment]
So yeah Steal version has no credit.
that is bad bro.
