### ISSUE TITLE
NO ISSUE, JUST BEAUTIFUL MENU (MISSING SOME BYPASSES AND METHODS)

### ISSUE THREAD

**Issue by mariarosalbba** [MHProDev/MHDDoS#47]
Hello, I didn't find another section in where I can review your script, I want to congratulate your work and love the script and the way you have researched on all DDoS methods, mostly L7 which is more complex. There are some things you did miss though and I would love to tell you privately. Please send me a DM 

Telegram
@chtv5

Sorry, TID was incorrect

**Comment by Adiru3** [comment]
> 

What methods are we talking about?

**Comment by MHProDev** [comment]
ok
