### ISSUE TITLE
Scam with me.

### ISSUE THREAD

**Issue by ismailh** [MHProDev/MHDDoS#49]
Scammer, no response, no support, fake script

**Comment by ismailh** [comment]
![image](https://user-images.githubusercontent.com/7131214/147709934-2d6d513b-bb16-4e33-b141-22dc2e24db8d.png)

**Comment by andress134** [comment]
> 

don;'t trust him this kid just copied some codes and created the menu of script all in one.
She use requests and cfscraper lib for bypass and this shit is very old

Also the almost lines from code (layer7) has been copied from other script made by Node like 3 years ago
Node#6354  this man has made the real script like 2-3 years ago and posted it for free on nulled  forum (you can found it)
This kid 'mhprodev' just copied real script and unique all lines all in one and created the menu

**Comment by MHProDev** [comment]
support telegram: https://t.me/MH_ProDev_IR
