### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by zpwrd** [MHProDev/MHDDoS#57]
When i want to use socks4.txt with ovh method i getting this exception:

Exception in thread Thread-6483:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "start.py", line 532, in ovh
    proxy = Choice(proxies).strip().split(":")
  File "/usr/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

**Comment by FortniBloxYT1** [comment]
socks4 is so bad,use socks5 or http proxies,and that error ocurre because you put the url like google.com and you need to put the url like https://google.com and you cant put ip on layer7 methods

**Comment by zpwrd** [comment]
> socks4 is so bad,use socks5 or http proxies,and that error ocurre because you put the url like google.com and you need to put the url like https://google.com and you cant put ip on layer7 methods

I tried to use socks5, but without changes.

**Comment by FortniBloxYT1** [comment]
the error is not if u using socks4 or 5 or http the error if because you putting the urls like:google.com
and you need to put the https:// like:https://google.com

**Comment by zpwrd** [comment]
> the error is not if u using socks4 or 5 or http the error if because you putting the urls like:google.com and you need to put the https:// like:https://google.com

I want to stress ip without domain, how to do?

**Comment by FortniBloxYT1** [comment]
http://IP
or https://IP
