### ISSUE TITLE
NTP Method

### ISSUE THREAD

**Issue by Spindermoon1** [MHProDev/MHDDoS#58]
Hello,
Can you tell me how to use the NTP method correctly. I can't manage to make it work. If you can communicate through discord or anything I would love to.

**Comment by FortniBloxYT1** [comment]
mhddos methods layer 4 shit

**Comment by n1109964492** [comment]
> 您好， 您能告诉我如何正确使用NTP方法吗？我无法让它工作。如果您可以通过不和谐或任何我愿意的方式进行交流。

The author ignores you because he just wants to scam you out of money to buy his private script, it's a scam

**Comment by Spindermoon1** [comment]
Well thanks for the info. Can you guys help me out tho. discord: TRiLON#9438

**Comment by Spindermoon1** [comment]
> 

No I mean, I don't get how the NTP method would work. The IP spoofing can't work since the ISP will block any packets you try to send with a faulty IP. What are my options then?

**Comment by Ggasdfg321** [comment]
> 思

我们在telegram联系

**Comment by FulltronService** [comment]
> > 
> 
> No I mean, I don't get how the NTP method would work. The IP spoofing can't work since the ISP will block any packets you try to send with a faulty IP. What are my options then?

Unfortunately the attacks in this script cannot execute Layer 4 via Proxy's. Since the owner is accepting my commits with improvements for the script I will be looking to see if it is possible to do Layer 4 using Proxy's or not. I will let you know soon

**Comment by theredcursed** [comment]
scam

**Comment by theredcursed** [comment]
scam

**Comment by theredcursed** [comment]
scam
