### ISSUE TITLE
UDP and TCP aren't working

### ISSUE THREAD

**Issue by thealt08** [MHProDev/MHDDoS#64]
Exception in thread Thread-337:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
  File "/usr/lib/python3.7/threading.py", line 865, in run
  File "start.py", line 325, in tcp
  File "/usr/lib/python3.7/socket.py", line 151, in __init__
OSError: [Errno 24] Too many open files

libgcc_s.so.1 must be installed for pthread_cancel to work
Aborted (core dumped)

I get this error one I start a tcp or udp flood

**Comment by ninjutsudev** [comment]
> Exception in thread Thread-337: Traceback (most recent call last): File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner File "/usr/lib/python3.7/threading.py", line 865, in run File "start.py", line 325, in tcp File "/usr/lib/python3.7/socket.py", line 151, in **init** OSError: [Errno 24] Too many open files
> 
> libgcc_s.so.1 must be installed for pthread_cancel to work Aborted (core dumped)
> 
> I get this error one I start a tcp or udp flood

That has nothing to do with MHDDoS, however. You can circumvent that problem by typing in the terminal "ulimit -n 65535".

I will try to make the script automatically do that job.
