### ISSUE TITLE
Can this tool flood a server with ip:custom port?

### ISSUE THREAD

**Issue by CKHO0O** [MHProDev/MHDDoS#7]
Can this tool flood a server with ip:custom port?

**Comment by CKHO0O** [comment]
Also, can it use with the local proxy list?

**Comment by MHProDev** [comment]
em can make a api and add to file start.py

**Comment by CKHO0O** [comment]
so will it be a new feature?
Because I suck at coding.

**Comment by linux21123** [comment]
Please put url/ip:port in that than you got many money as donation for this bro this script is REALLY nice <3

**Comment by MHProDev** [comment]
ok can u edit and add ur own proxy list api 
![image](https://user-images.githubusercontent.com/63018646/111493681-0b817180-8753-11eb-8235-12de7fb972e7.png)

**Comment by MHProDev** [comment]
i soon update script for proxy api

**Comment by linux21123** [comment]
n1c3 ❤

**Comment by linux21123** [comment]
We want attack Server's and Routers with that Script that is really nice :3

**Comment by linux21123** [comment]
wtf why you closed this??
