### ISSUE TITLE
error install requirements

### ISSUE THREAD

**Issue by hoaan1995** [MHProDev/MHDDoS#71]

**Comment by hoaan1995** [comment]
error install requirements

**Comment by MHProDev** [comment]
what error ?

**Comment by hoaan1995** [comment]
> @hoaan1995 what error ?

![image](https://user-images.githubusercontent.com/91445089/152784228-5333f61e-986d-4662-bce7-8c72a3575711.png)


ummm is not working

**Comment by hoaan1995** [comment]
> @hoaan1995 what error ?

oh sorry i forgot to update pip3 sorry i was careless

**Comment by MHProDev** [comment]
:|
