### ISSUE TITLE
USING ERROR PLS HELP!!!

### ISSUE THREAD

**Issue by hoaan1995** [MHProDev/MHDDoS#74]
PLEASE ACCEPT MY FRIENDS AND HELP ME FIX THIS BUG VCxL9001#6134

**Comment by Melih-GMC2** [comment]
huh

**Comment by MHProDev** [comment]
send error

**Comment by hoaan1995** [comment]
> send error

proxy checked error

**Comment by MHProDev** [comment]
ss ?

**Comment by bntr00t** [comment]
> I can't understand users asking for help without saying what is happening.... I must be from another world...

MH is literally the guy who has to see this shit everyday, and he doesn't care, I love it.
