### ISSUE TITLE
proxy problem

### ISSUE THREAD

**Issue by Melih-GMC2** [MHProDev/MHDDoS#76]
whenever i use proxies, it just checks proxies for 20-30 seconds and when it finishes, it just says "Empty Proxy File, Running flood witout proxy". please fix this

**Comment by bntr00t** [comment]
Put your proxies in MHDDoS/files/proxys/proxy.txt

Then run with python start.py method url proxytype etc...

Make sure you define everything right, MHDDoS reads automatically from files/proxys
