### ISSUE TITLE
SHIT PROGRAM

### ISSUE THREAD

**Issue by FortniBloxYT1** [MHProDev/MHDDoS#78]
ONLY 1000 THREADS AND 100 MULTIPLE WTF IS THIS SHIT CODE
UR TRASH PROXY METHODS ATTACK SO WEAK
AND UR METHODS CANT BYPASS ANYTHING,MAKE A METHOD FOR BYPASS CLOUDFLARE UAM FUCKING STUPID

**Comment by OscarAkaElvis** [comment]
> ONLY 1000 THREADS AND 100 MULTIPLE WTF IS THIS SHIT CODE UR TRASH PROXY METHODS ATTACK SO WEAK AND UR METHODS CANT BYPASS ANYTHING,MAKE A METHOD FOR BYPASS CLOUDFLARE UAM FUCKING STUPID

Ungrateful idiot. Please admin, close this issue and ban this kind of shitty user. His comment don't deserve more than the time you take to click on ban.

**Comment by MHProDev** [comment]
Thanks for your review, I will try my best to make the script better at the next update. Love from your friendly developer!

**Comment by Monkeyman1337s** [comment]
bro you know u can increase the threads and multiple by yourself , idk whats wrong with you but i can actualy use 50K threads on this script .
